# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-02 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0002_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='tab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sales', models.CharField(max_length=200)),
                ('Date', models.DateField()),
            ],
        ),
    ]
